name: Manish Portfolio
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [14.x, 15.x]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     - name: npm install & create build
  #     - run: |
  #         npm install
  #         npm run build
  #     - env:
  #         CI: true

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to aws Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          # ARGS: "-rltgoDzvO --delete"
          ARGS: "-av"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: "~/manish-hedau/portfolio/"
          EXCLUDE: "/dist/, /node_modules/, .git"

      - name: Executing multiple commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            # curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
            # . ~/.nvm/nvm.sh
            # nvm instal 18
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/manish-hedau/portfolio/  
            # git pull origin main
            npm install
            npm run build
            # pm2 start "npm run start" --name "portfolio"
            sudo pm2 restart portfolio
